### PR TITLE
sass file structure

### PR DESCRIPTION
**Pull request by AlexBrown-appnovation**
The following PR is my proposed SASS folder/file structure. I've included a README.md file for some documentation on the structure which is based on a SMACSS/Drupal hybrid approach.

SASS files will be kept in the sass/ folder, while the output will be in the /css/style.css file.

A separate PR will be made for the initial Gulp.js set up that is described in the documentation.

### CODE REVIEW

**Comment by fureigh** [comment]
@AlexBrown-appnovation I'm interpreting the "Wip" in this PR's title that you're in the process of working on this. Holler (by assigning it to me or just saying it's ready for review) when you do want other eyes on it. Thanks!

**Comment by AlexBrown-appnovation** [comment]
@fureigh I think this is good to go for yours or anyone elses review as it is!

**Comment by AlexBrown-appnovation** [comment]
Removed WIP title on PR.

**Comment by iris-i** [comment]
@fureigh it'll be great to have this PR merged too. I believe this is the missing piece for the blocker I had with getting started with gulp for compiling style changes in #26. The sass file structure is vital for setting up custom drupal-specific styles.

**Comment by AlexBrown-appnovation** [comment]
@fureigh is there anything I can take care of to help this PR make it in to the 7.x branch?

**Comment by fureigh** [comment]
@AlexBrown-appnovation @iris-i Thanks for this, and sorry for the delay! Merging.

**Comment by iris-i** [comment]
Thanks @fureigh! Np at all.

**Pull request merged**
